name = "gnat_native"
version = "15.2.1001"
provides = ["gnat=15.2.1001"]
description = "The GNAT Ada compiler with backports"
website = "https://github.com/Prunt3D/gcc"
maintainers = ["Liam Powell <liam@liampwll.com>"]
maintainers-logins = ["liampwll"]
licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"
auto-gpr-with = false
notes = "Built from GCC 15.2.1001 commit 7aa5d4b8c029f6902e24022fb6cfefad7426294a"

[configuration]
disabled = true

[environment."case(os)".linux]
PATH.prepend = "${CRATE_ROOT}/usr/local/bin"
LIBRARY_PATH.prepend = "${CRATE_ROOT}/usr/local/lib64"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/usr/local/lib64"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/usr/local/lib64"

[origin."case(os)".linux."case(host-arch)".x86-64]
binary = true
url = "https://github.com/Prunt3D/prunt_alire_index/releases/download/gnat-15.2.1001/gnat-x86_64-linux-15.2.1001.tar.gz"
hashes = ["sha256:d1f1051f3b81c65c1f1d91fc3d8369d0d024a9760603a59570891bbdd38b60e3"]
