name = "gnat_native"
version = "16.2.1002"
provides = ["gnat=16.2.1002"]
description = "GCC with C, Ada, and Fortran enabled, plus backports"
website = "https://github.com/Prunt3D/gcc"
maintainers = ["Liam Powell <liam@liampwll.com>"]
maintainers-logins = ["liampwll"]
licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"
auto-gpr-with = false
notes = "Built from GCC 16.2.1002 commit 0eb9fb2272496dba9e56ab25acbe15c6123166c3"

[configuration]
disabled = true

[environment."case(os)".linux]
PATH.prepend = "${CRATE_ROOT}/local/bin"
LIBRARY_PATH.prepend = "${CRATE_ROOT}/local/lib64"
LD_LIBRARY_PATH.prepend = "${CRATE_ROOT}/local/lib64"
LD_RUN_PATH.prepend = "${CRATE_ROOT}/local/lib64"


[origin."case(os)".linux."case(host-arch)".x86-64]
binary = true
url = "https://github.com/Prunt3D/prunt_alire_index/releases/download/gnat-16.2.1002/gnat-x86_64-linux-16.2.1002.tar.gz"
hashes = ["sha256:89b2bd848ef42d0c1c50ab14b672fd8d27252d6d28ead361fa5177a106a7f84c"]


[origin."case(os)".linux."case(host-arch)".aarch64]
binary = true
url = "https://github.com/Prunt3D/prunt_alire_index/releases/download/gnat-16.2.1002/gnat-aarch64-linux-16.2.1002.tar.gz"
hashes = ["sha256:29268f4138217ecd62c43a0558946457b31657733bac9a068908a19f83ba4c64"]
